import React from 'react';

import { render } from 'tests/utils';
import { rollbar } from 'monitoring/rollbar';

jest.mock('monitoring/rollbar');

global.console.error = jest.fn();

const Bomb = () => {
  throw new Error('ðŸ’¥ CABOOM ðŸ’¥');
};

test('ErrorMonitoringProvider: component error', async () => {
  try {
    render(<Bomb />);
  } catch {
    // Nothing
  }

  expect(console.error).toHaveBeenCalledTimes(2);
  expect(
    console.error.mock.calls[1][0].startsWith(
      'The above error occurred in the <Bomb> component:'
    )
  ).toBe(true);
  expect(
    console.error.mock.calls[0][0].startsWith(
      'Error: Uncaught [Error: ðŸ’¥ CABOOM ðŸ’¥]'
    )
  ).toBe(true);
  expect(rollbar.error).toHaveBeenCalledTimes(1);
  const rollbarCall = rollbar.error.mock.calls[0];
  expect(rollbarCall[0]).toStrictEqual('ðŸ’¥ CABOOM ðŸ’¥');
  console.log(rollbarCall[1]);
  expect(rollbarCall[1].startsWith('Error: ðŸ’¥ CABOOM ðŸ’¥')).toBe(true);
});
